apiVersion: v1
kind: Namespace
metadata:
  name: docker-demo-namespace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo-deployment
  namespace: docker-demo-namespace
spec:
  selector:
    matchLabels:
      app: spring-boot-k8s
  replicas: 4
  template:
    metadata:
      labels:
        app: spring-boot-k8s
    spec:
      containers:
        - name: spring-docker-demo-app-container
          image: spring-docker-app:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8282

---
apiVersion: v1
kind: Service
metadata:
  name: docker-demo-service
  namespace: docker-demo-namespace
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 9292
      targetPort: 8282
  type: NodePort
