apiVersion: v1
kind: Service
metadata:
  name: docker-demo-service
  namespace: docker-demo-namespace
spec:
  selector:
    app: spring-boot-k8s
  ports:
    - protocol: TCP
      port: 9292
      targetPort: 8282
  type: NodePort